// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hatggckilchiwitqexau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhdGdnY2tpbGNoaXdpdHFleGF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MTk5NzgsImV4cCI6MjA2NTk5NTk3OH0.27dnGtNQfZ0KZrVg1QdARaskY5vLv6gt_uOtLzH7J94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);